on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: building and testing the action
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Build, using rollup
        run: |
          npm ci
          npm run build
      - name: Test action linting SQL without error
        uses: ./
        with:
          path: './test/test.sql'
      - name: Test action linting SQL with error
        uses: ./
        continue-on-error: true
        with:
          path: './test/test1.sql'
